# -*- coding: utf-8 -*-
"""PythonImageManipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRWpuOPoR-dVjbcRWyUQSmlEyT5Nd4Z2
"""

!pip install onnxruntime rembg pillow ipywidgets

from rembg import remove
import io
from PIL import Image, ImageOps
from ipywidgets import widgets
from IPython.display import display, clear_output

def remove_backgroud(image):
  input_image = Image.open(image)
  output_image = remove(image)
  return Image.open(io.BytesIO(output_image))

def convert_to_8bit(image):
  return image.convert("p", palette = Image.ADAPTIVE)

def convert_black_and_white(image):
  return image.conver("L")

def process_image(change):
  clear_output(wait=True)
  display(uploader, transform_options, process_button)
  if uploader.value :
    image_bytes = uploader.value[list(uploader.value.key()[0]['content'])]
    original_image = Image.open(io.BytesIO(image_bytes))
    processed_image = remove_backgroud(image_bytes)

    if transform_options.value == '8-Bit':
      processed_image = convert_to_8bit(processed_image)
    elif transform_options.value == 'Black and White':
      processed_image = convert_black_and_white(processed_image)

      display(widgets.HTML("<h3> Orginal Image </h3>"))
      display(original_image)
      display(widgets.HTML("<h3> Processed Image </h3>"))
      display(processed_image)

      processed_image.save('processed_image.png')
      display(widgets.HTML("<h3> Processed image saved as 'processed_image.png'</h3>"))

uploader = widgets.FileUpload(accept='image/*', mutiple=False)
transform_options = widgets.Dropdown(options=['Original(Background removed)', '8-Bit', 'Black and White'],
    value = "Original(Background removed)",
    description = "Transform : "
    )


process_button = widgets.Button(description="Process Image")
process_button.on_click(process_image)

display(widgets.HTML("<h2> Image Background Removed </h2>"))
display(uploader, transform_options, process_button)

